force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Purchase_Order_Invoice__c/Purchase_Order_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Salesforce Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>SRN Generated</fullName>
            </value>
            <value>
                <fullName>GRN Generated</fullName>
            </value>
            <value>
                <fullName>UTR Generated</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order_Invoice__c/fields/UTR__c.field-meta.xml
<CustomField>
    <fullName>UTR__c</fullName>
    <externalId>true</externalId>
    <label>UTR</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Purchase_Order_Invoice__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Order Invoices</relationshipLabel>
    <relationshipName>Purchase_Order_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/POInvoiceService.cls
@RestResource(urlMapping='/invoice/*')
global without sharing class POInvoiceService {
    
    @HttpPost
    global static String createPOInvoice() {
        //{"Invoice Details":[{"Invoice Number":"BP/2425/0000729","Name":"TELNET SPACE","Sales Force ID":"INV-0000008","UTR":"","Status":"SRN Generated"}]}
        RestRequest req = RestContext.request;
        String jsonString = req.requestBody.toString();
        jsonString = jsonString.substringAfter(':[');
        jsonString = jsonString.removeEnd(']}'); 
        System.debug('jsonString :: '+jsonString);
        Map<String, Object> invoiceData = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
        
        if((String) invoiceData.get('Sales Force ID') != ''){
            String accountName = (String) invoiceData.get('Name');
            List<Account> vendor = new List<Account>([Select Id,Name from Account where Name =:accountName limit 1]);
            String buyFromVendorNo = (String) invoiceData.get('Sales Force ID');
            Purchase_Order_Invoice__c invoice = [SELECT Id FROM Purchase_Order_Invoice__c where Name =:buyFromVendorNo limit 1];
            invoice.Invoice_Number__c = (String) invoiceData.get('Invoice Number');
            invoice.Vendor__c = vendor[0].Id;
            invoice.UTR__c = (String) invoiceData.get('UTR');
            invoice.Invoice_Status__c  = (String) invoiceData.get('Status');
            
            update invoice;
            
            
            return 'success';
        }else{
            return 'Salesforce Id is not found';
        }
    }
}