force-app/main/default/objects/Account/fields/GST_Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>GST_Vendor_Type__c</fullName>
    <label>GST Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>UnRegistered</fullName>
            </value>
            <value>
                <fullName>Composite</fullName>
            </value>
            <value>
                <fullName>Import</fullName>
            </value>
            <value>
                <fullName>Exempted</fullName>
            </value>
            <value>
                <fullName>SEX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/No__c.field-meta.xml
<CustomField>
    <fullName>No__c</fullName>
    <externalId>true</externalId>
    <label>Vendor No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Code__c</fullName>
    <label>Payment Method Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms_Code__c</fullName>
    <label>Payment Terms Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Responsibility_centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Responsibility_centre_Code__c</fullName>
    <description>Responsibility centre Code</description>
    <externalId>true</externalId>
    <label>Responsibility centre Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/PO_Header__c/PO_Header__c.object-meta.xml
<CustomObject>
    <label>PO Header</label>
    <nameField>
        <label>PO Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PO Header</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PO_Header__c/fields/Location_GST_Reg_No__c.field-meta.xml
<CustomField>
    <fullName>Location_GST_Reg_No__c</fullName>
    <label>Location GST Reg. No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Location_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_State_Code__c</fullName>
    <label>Location State Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/MSME_Status__c.field-meta.xml
<CustomField>
    <fullName>MSME_Status__c</fullName>
    <label>MSME Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Pay_to_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Pay_to_Address_2__c</fullName>
    <label>Pay-to Address 2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Pay_to_City__c.field-meta.xml
<CustomField>
    <fullName>Pay_to_City__c</fullName>
    <label>Pay-to City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Pay_to_Name__c.field-meta.xml
<CustomField>
    <fullName>Pay_to_Name__c</fullName>
    <label>Pay-to Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Posting_Description__c.field-meta.xml
<CustomField>
    <fullName>Posting_Description__c</fullName>
    <label>Posting Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_ID__c</fullName>
    <label>Project ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Purchase_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_No__c</fullName>
    <label>Purchase Order No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Responsibility_Center__c.field-meta.xml
<CustomField>
    <fullName>Responsibility_Center__c</fullName>
    <label>Responsibility Center</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Prepayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PO Header (Vendor)</relationshipLabel>
    <relationshipName>PO_Header</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Vendor_GST_Reg_No__c.field-meta.xml
<CustomField>
    <fullName>Vendor_GST_Reg_No__c</fullName>
    <label>Vendor GST Reg. No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Header__c/fields/Your_Reference__c.field-meta.xml
<CustomField>
    <fullName>Your_Reference__c</fullName>
    <label>Your Reference</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <label>Assigned User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/BRANCH_CODE__c.field-meta.xml
<CustomField>
    <fullName>BRANCH_CODE__c</fullName>
    <label>BRANCH CODE</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Buy_from_Country_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Buy_from_Country_Region_Code__c</fullName>
    <label>Buy-from Country/Region Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Buy_from_Vendor_No__c.field-meta.xml
<CustomField>
    <fullName>Buy_from_Vendor_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buy-from Vendor No.</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PO_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PO_Header1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Dept_Code__c.field-meta.xml
<CustomField>
    <fullName>Dept_Code__c</fullName>
    <label>Dept Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <label>Entity Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/GST_Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>GST_Vendor_Type__c</fullName>
    <label>GST Vendor Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <label>Location Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Pay_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Pay_to_Address__c</fullName>
    <label>Pay-to Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Pay_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Pay_to_Contact__c</fullName>
    <label>Pay-to Contact</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Pay_to_Name__c.field-meta.xml
<CustomField>
    <fullName>Pay_to_Name__c</fullName>
    <label>Pay-to Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Pay_to_Vendor_No__c.field-meta.xml
<CustomField>
    <fullName>Pay_to_Vendor_No__c</fullName>
    <label>Pay-to Vendor No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Payment_Method_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Code__c</fullName>
    <label>Payment Method Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Payment_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms_Code__c</fullName>
    <label>Payment Terms Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/PO_Created_By__c.field-meta.xml
<CustomField>
    <fullName>PO_Created_By__c</fullName>
    <label>PO Created By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Posting_Description__c.field-meta.xml
<CustomField>
    <fullName>Posting_Description__c</fullName>
    <label>Posting Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Purchase_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_No__c</fullName>
    <externalId>true</externalId>
    <label>Purchase Order No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Uniquey_Key__c.field-meta.xml
<CustomField>
    <fullName>Uniquey_Key__c</fullName>
    <externalId>true</externalId>
    <label>Uniquey Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>PO_Header</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vendor_Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Invoice_No__c</fullName>
    <label>Vendor Invoice No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Your_Reference__c.field-meta.xml
<CustomField>
    <fullName>Your_Reference__c</fullName>
    <label>Your Reference</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{0000000}</displayFormat>
        <label>PO Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/BRANCH_CODE__c.field-meta.xml
<CustomField>
    <fullName>BRANCH_CODE__c</fullName>
    <label>BRANCH CODE</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Dept_Code__c.field-meta.xml
<CustomField>
    <fullName>Dept_Code__c</fullName>
    <label>Dept Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <label>Entity Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <label>Location Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Responsibility_Center__c.field-meta.xml
<CustomField>
    <fullName>Responsibility_Center__c</fullName>
    <label>Responsibility Center</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POHeaderService.cls
@RestResource(urlMapping='/poheader/*')
global class POHeaderService {
    
    @HttpPost
    global static String createPOHeader() {
        
        RestRequest req = RestContext.request;
        String jsonString = req.requestBody.toString();
        System.debug('jsonString :: '+jsonString);


        Map<String, Object> poData = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
System.debug('poData>>'+poData);
System.debug('poData>>'+poData.values()); 
 
System.debug(poData.keySet()); 

        Account company = null;
        if (poData.containsKey('Purchase Header Detail')) {
                       Map<String,Object> poHeaderDetailMap = (Map<String,Object>) poData.get('Purchase Header Detail'); // Correctly getting the list of Purchase Header Details
            List<Purchase_Order__c> orderList = new List<Purchase_Order__c>();

            
                // Convert dates from the JSON
                Date orderDateConverted = Date.valueOf((String) poHeaderDetailMap.get('Order Date'));
                Date postingDateConverted = Date.valueOf((String) poHeaderDetailMap.get('Posting Date'));
                Date expectedReceiptDateConverted = Date.valueOf((String) poHeaderDetailMap.get('Expected Receipt Date'));
                Date documentDateConverted = Date.valueOf((String) poHeaderDetailMap.get('Document Date'));
                
                // Lookup vendor and company accounts
                String buyFromVendorNo = (String) poHeaderDetailMap.get('Buy-from Vendor No.');
                String respCode = (String) poHeaderDetailMap.get('Responsibility Center');
                Account vendorAccount = [SELECT Id FROM Account WHERE No__c = :buyFromVendorNo LIMIT 1];
                company = [SELECT Id FROM Account WHERE Responsibility_centre_Code__c = :respCode LIMIT 1];

                // Create Purchase Order Header Record
                Purchase_Order__c order = new Purchase_Order__c(
                    Purchase_Order_No__c = (String) poHeaderDetailMap.get('No.'),
                    Buy_from_Vendor_No__c = vendorAccount.Id,
                    Pay_to_Vendor_No__c = (String) poHeaderDetailMap.get('Pay-to Vendor No.'),
                    Pay_to_Name__c = (String) poHeaderDetailMap.get('Pay-to Name'),
                    Pay_to_Address__c = (String) poHeaderDetailMap.get('Pay-to Address'),
                    Pay_to_Address_2__c = (String) poHeaderDetailMap.get('Pay-to Address 2'),
                    Pay_to_City__c = (String) poHeaderDetailMap.get('Pay-to City'),
                    Pay_to_Contact__c = (String) poHeaderDetailMap.get('Pay-to Contact'),
                    Your_Reference__c = (String) poHeaderDetailMap.get('Your Reference'),
                    Order_Date__c = orderDateConverted,
                    Posting_Date__c = postingDateConverted,
                    Posting_Description__c = (String) poHeaderDetailMap.get('Posting Description'),
                    Payment_Terms_Code__c = (String) poHeaderDetailMap.get('Payment Terms Code'),
                    Location_Code__c = (String) poHeaderDetailMap.get('Location Code'),
                    Project_ID__c = (String) poHeaderDetailMap.get('Project ID'),
                    Branch_Code__c = (String) poHeaderDetailMap.get('BRANCH CODE'),
                    Dept_Code__c = (String) poHeaderDetailMap.get('Dept Code'),
                    Currency_Code__c = (String) poHeaderDetailMap.get('Currency Code'),
                    Vendor_Invoice_No__c = (String) poHeaderDetailMap.get('Vendor Invoice No.'),
                    Buy_from_Country_Region_Code__c = (String) poHeaderDetailMap.get('Buy-from Country/Region Code'),
                    Document_Date__c = documentDateConverted,
                    Payment_Method_Code__c = (String) poHeaderDetailMap.get('Payment Method Code'),
                    Status__c = (String) poHeaderDetailMap.get('Status'),
                    Responsibility_Center__c = (String) poHeaderDetailMap.get('Responsibility Center'),
                    PO_Created_By__c = (String) poHeaderDetailMap.get('Assigned User ID'),
                    GST_Vendor_Type__c = (String) poHeaderDetailMap.get('GST Vendor Type'),
                    Vendor_GST_Reg_No__c = (String) poHeaderDetailMap.get('Vendor GST Reg. No.'),
                    Location_State_Code__c = (String) poHeaderDetailMap.get('Location State Code'),
                    Location_GST_Reg_No__c = (String) poHeaderDetailMap.get('Location GST Reg. No.'),
                    State__c = (String) poHeaderDetailMap.get('State'),
                    MSME_Status__c = (String) poHeaderDetailMap.get('MSME Status'),
                    Entity_Name__c = (String) poHeaderDetailMap.get('Entity Name'),
                    Vendor__c = vendorAccount.Id,
                    Company__c = company.Id,
                    Uniquey_Key__c = company.Id+'_'+(String) poHeaderDetailMap.get('No.'),
                    Assigned_User__c = (String) poHeaderDetailMap.get('Assigned User ID')
                );
                
                orderList.add(order);
            
            
            if (!orderList.isEmpty()) {
                upsert orderList Uniquey_Key__c;
                
                // Map to hold the Ids of the inserted Purchase_Order__c records
                Map<String, Id> poHeaderIdMap = new Map<String, Id>();
                for (Purchase_Order__c order1 : orderList) {
                    poHeaderIdMap.put(order1.Uniquey_Key__c, order1.Id);
                }
                
                List<Purchase_Order_Line__c> orderLineList = new List<Purchase_Order_Line__c>();
                
                    
                    if (poHeaderDetailMap.containsKey('Purchase Line Detail')) {
                        List<Object> poLineDetailsList = (List<Object>) poHeaderDetailMap.get('Purchase Line Detail');
                        
                        for (Object poLineDetail : poLineDetailsList) {
                            Map<String, Object> poLineDetailMap = (Map<String, Object>) poLineDetail;
                            System.debug('Purchase Line Detail>>>' + poLineDetailMap);
                            
                            Id poHeaderId = poHeaderIdMap.get(company.Id+'_'+(String) poHeaderDetailMap.get('No.'));
                            
                            // Create Purchase Order Line Record
                            Purchase_Order_Line__c orderLine = new Purchase_Order_Line__c(
                                PO_Header__c = poHeaderId,
                                Buy_from_Vendor_No__c = (String) poLineDetailMap.get('Buy-from Vendor No.'),
                                Document_No__c = (String) poLineDetailMap.get('Document No.'),
                                Line_No__c = String.valueOf(poLineDetailMap.get('Line No.')),
                                Description__c = (String) poLineDetailMap.get('Description'),
                                Unit_of_Measure__c = (String) poLineDetailMap.get('Unit of Measure'),
                                Quantity__c = (Decimal) poLineDetailMap.get('Quantity'),
                                Outstanding_Quantity__c = (Decimal) poLineDetailMap.get('Outstanding Quantity'),
                                Direct_Unit_Cost__c = String.valueOf(poLineDetailMap.get('Direct Unit Cost')),
                                Unit_Cost_LCY__c = String.valueOf(poLineDetailMap.get('Unit Cost (LCY)')),
                                Amount__c = String.valueOf(poLineDetailMap.get('Amount')),
                                Project_ID__c = (String) poLineDetailMap.get('Project ID (Dimension)'),
                                Outstanding_Amount__c = Decimal.valueOf(String.valueOf(poLineDetailMap.get('Outstanding Amount'))),
                                Responsibility_Center__c = (String) poLineDetailMap.get('Responsibility Center'),
                                Unique_Key__c  = poHeaderId+'_'+poLineDetailMap.get('Line No.')
                            );
                            
                            orderLineList.add(orderLine);
                        }
                    }
                
                
                if (!orderLineList.isEmpty()) {
                    upsert orderLineList Unique_Key__c ;
                }
                
                return 'Purchase order created successfully';
            } else {
                return 'No valid purchase order details found';
            }
        }
        
        return 'Invalid JSON';
    }
}